kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-workspace
  namespace: cicd-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3
  volumeMode: Filesystem