apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by: argocd-control-plane
    operator:
      tekton:
        dev/enable-annotation=enabled: enabled
  name: cicd-pipelines
spec:
  finalizers:
    - kubernetes