apiVersion: v1
kind: Namespace
metadata:
  name: cicd-pipelines # namespace to be managed by an existing Argo CD instance
  labels:
    argocd.argoproj.io/managed-by: argocd-control-plane #openshift-gitops #argocd-control-plane
spec:
  finalizers:
    - kubernetes