apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by: argocd-control-plane #openshift-gitops #argocd-control-plane
  name: cicd-pipelines
spec:
  finalizers:
    - kubernetes