apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by: argocd-control-plane #openshift-gitops #argocd instance ns
  name: openshift-logging
spec:
  finalizers:
    - kubernetes