apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argcd-openshift-pipelines
  namespace: argocd-control-plane #openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: clusterlogging
    repoURL: https://github.com/ksunilkumar007/openshift-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false