kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-sa
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: cicd-pipelines
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: argocd-control-plane
  - kind: ServiceAccount
    name: openshift-gitops-applicationset-controller
    namespace: openshift-gitops
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin